### PR TITLE
Paged content

### PR DESCRIPTION
**Pull request by bondjimbond**
I added some functions to detect whether the preserved object is a Newspaper, Book, or Newspaper Issue object, and add PRESERVATION datastreams to its children accordingly.

This functionality is redundant if Islandora Bagit gets paged content support, but I don't know what the status of that is at the moment.

Note that this PR will need to be updated anyway - need to add a check on ingest - if object is newspaperIssue or page, check parent and preserve if necessary.

@mjordan your thoughts?

### CODE REVIEW

**Comment by bondjimbond** [comment]
Now set up to preserve child pages of new books and newspaper issues on ingest.

@mjordan what's the better solution -- this PR, or fixing the Bag-It module to support paged objects?

**Comment by mjordan** [comment]
Bagit module needs that work done regardless. In the current PR, how would you reconstruct the page -> parent relationship, using the page's RELS-EXT?

**Comment by bondjimbond** [comment]
That's pretty much the case. Same as how you'd reconstruct a collection (noting of course that at the moment, Bagit doesn't let you generate bags for collection objects -- I've got a PR in queue that only partially addresses that).

Preference perhaps would be to bag up entire books/issues with all their pages, but I'm not sure how well OwnCloud sync would perform with extremely large files (say 300 pages of 500 MB TIFFs plus derivatives).

**Comment by bondjimbond** [comment]
re updating Islandora Bagit to support paged and compound objects... 

Would it be sufficient to make just a couple of tweaks?

Here's your query:

```
function islandora_bagit_get_batch_members($islandora_object) {
  // List of objects to create Bags for.
  $objects_to_bag = array();

  // Query the rindex to get all the objects that have a 'isMemberOfCollection'
  // relationship with the specified collection and add all their PIDs to the
  // list.
  $tuque = islandora_get_tuque_connection();
  $ri_query = <<<EOQ
SELECT ?object
FROM <#ri>
WHERE {
  ?object <fedora-rels-ext:isMemberOfCollection> <info:fedora/{$islandora_object->id}>
}
EOQ;
```

Could you simply modify it to get all objects that have the `isMemberOfCollection` relationship OR isMemberOf OR isConstituentOf?

And then under `function islandora_bagit_create_bag($islandora_object)`:
```
  // First, check to see if the object is a collection, and if it is,
  // reroute to the relevant batch function.
  foreach ($islandora_object as $ds) {
    if ($ds->id == 'COLLECTION_POLICY') {
      if (variable_get('islandora_bagit_multiple_bag_type', 'object') == 'object') {
        islandora_bagit_create_object_bag_batch($islandora_object);
      }
      elseif (variable_get('islandora_bagit_multiple_bag_type', 'object') == 'collection') {
        islandora_bagit_create_collection_bag_batch($islandora_object);
      }
      elseif (variable_get('islandora_bagit_multiple_bag_type', 'object') == 'no_children') {
        break;
      }
      return array();
    }
```

the IF statement could be modified to include collections OR compounds OR books OR newspaper issues OR newspapers.

The only problem then is how to handle bagging newspaper issues recursively if you're bagging a newspaper.

**Comment by bondjimbond** [comment]
@mjordan Ping to check up on where things are with Islandora Bagit. Any thoughts on the comment above?

**Comment by mjordan** [comment]
> Could you simply modify it to get all objects that have the isMemberOfCollection relationship OR isMemberOf OR isConstituentOf?

sounds like it would get all the objects we'd want, but like you say, the problem remains of how these objects should fit into a particular Bag. Personally I favor the one-Bag-per-smallest-object-unit (so each page would be in its own Bag) with each object's relationship expressed in a bag-info.txt file in addition to in the object's RELS-EXT.

**Comment by bondjimbond** [comment]
That approach makes sense to me, and is the best way to make sure syncing works in WestVault. It's a bit out of sync with the way Collection bags work, though, isn't it?

For Collections, we have three options:
- Bag up the entire collection and its children
- Bag children individually
- Bag just the Collection object

Shall we do paged objects similarly - i.e. let the repository admin decide?

**Comment by mjordan** [comment]
@bondjimbond yes, it is out of sync with the way collection Bags work, but that's the way we implemented collection Bags. I wouldn't do it that way today.

I am all for allowing the repo admin to decide, but the complexity of providing all three options is very high (look at the terrible stuff I did to get single-Bag collection Bags to work). I don't have the capacity to implement all three ways of doing it.

**Comment by bondjimbond** [comment]
Haha, well that's fine; one bag per page is a good way to go.

I can do testing if you get a PR in.

**Comment by mjordan** [comment]
@bondjimbond I am now thinking that instead of changing the core Bagit module to do this, getting all the pages of a book in an implementation of `hook_islandora_bagit_post_create()` might be less disruptive. I'm concerned that modifying the Bagit module to include this functionality will introduce regression bugs.

My idea here is in the hook, you test that the object is a book; if it is, get all of its pages and loop through each one, creating a Bag for it. The one issue you'd need to watch for is a potential infinite loop. Specifically, when a page Bag is created, this implementation of the post_create hook would fire again on the same object. Logic within the implementation would have to do something like check to see if a Bag for that object already existed (e.g. `if (!file_exists('path/to/bag/with_pages/pid.zip'))`). I am happy to provide code to get you going. In fact, it might be possible to create a separate module that provided similar functionality for all complex object types.

(In trying out this approach I did find a bug in the core module; PR is at https://github.com/Islandora/islandora_bagit/pull/61.)

**Comment by mjordan** [comment]
I started https://github.com/mjordan/islandora_bagit_complex and am still testing it, but it appears to work as intended.

**Comment by bondjimbond** [comment]
@mjordan Is that much different, then, from what I've done in this pull?

If you're not going to change the core module, then why not just use the code that's written here?

**Comment by mjordan** [comment]
The code in this PR is specific to Islandora Westvault. Anyone can use the new module.

**Comment by bondjimbond** [comment]
Ah, makes sense

Should be able to reuse some of this code, though -- the cmodel loop bit anyway.

What's the risk of putting it in islandora_bagit, exactly? Could include it, set it "off" by default, and turn it on as an admin option?

**Comment by bondjimbond** [comment]
ack, I didn't even notice the followup comment with the new module in it
I'll check it out

**Comment by bondjimbond** [comment]
What if someone bags a newspaper issue (rather than a whole newspaper)? We'll need the paged bagging functionality for that as well.

**Comment by bondjimbond** [comment]
Discarding in favour of #36.

**Pull request closed without merging**
