### PR TITLE
Using islandora_bagit_complex

### PR DESCRIPTION
**Pull request by bondjimbond**
This approach to complex objects makes use of islandora_bagit_complex to grab and bag pages.

Complications:

- Newspaper Issues may or may not be automatically preserved when added to a preserved Newspaper - this needs to be tested
- Same with Compound objects - they probably aren't but should be
- Requires that the user has particular Bagit settings (bag only the newspaper and not the children) which don't exist yet
- Do we use islandora_bagit_complex to deal with compound children, or skip its approach and just use our own?

### CODE REVIEW

**Comment by bondjimbond** [comment]
@mjordan Can't figure out why I'm getting a 500 error...

```
function islandora_westvault_islandora_compound_object_children_added_to_parent($object, $parent_pids) {
  module_load_include('module', 'islandora_compound_object');
  foreach ($parent_pids AS $parent_pid) {
    $parent_test = islandora_object_load($parent_pid);
    $ds = $parent_test["PRESERVATION"];
    if (!empty($ds)) {
      module_load_include('inc', 'islandora_westvault', 'includes/management_form');
      islandora_westvault_add_preservation_datastream($object);
    }
  }
}
```

The above code invokes a hook in islandora_compound_object that triggers when an object is added to a compound parent. Every part of it works (tested with dd) except they key piece: `islandora_westvault_add_preservation_datastream($object);` causes a 500 error with no visible reason.

Added `dd()` notes within the `islandora_westvault_add_preservation_datastream()` function and nothing appears, so it looks like the act of even calling the function breaks things.

Any ideas?

**Comment by mjordan** [comment]
Anything in your apache error.log?

**Comment by bondjimbond** [comment]
@mjordan It looks like the `$object` passed in `function islandora_westvault_islandora_compound_object_children_added_to_parent($object, $parent_pids)` is an array and not an object (the 'object' is item [0] in the array). I was having trouble working with that... Even using `$object['0']` wasn't getting me a valid object.

After some struggling I managed to acquire the "object" by extracting the PID like so:

```
$object = $object['0'];
$compound_child = islandora_object_load($object->id);
```

Now the automatic assignment of the PRESERVATION datastream to compound children is working.

**Comment by bondjimbond** [comment]
@mjordan Would you be willing to test this branch, at this point? Although I acknowledge that properly testing this would be a bit of work, so if you're too busy, no worries.

- In Islandora Bagit, under Complex Objects, check off Books and Newspaper Issues. Leave Compound and Newspapers unchecked.
- Have a few objects handy: a Book, a Newspaper with a couple of issues in it, a Compound Object with one or two children, and a regular object on its own
- Manage the Book, Newspaper, and Compound Object and turn on Preservation for each. Compound children and Newspaper Issue objects should all get PRESERVATION datastreams applied automatically.
- Run `drush -u 1 westvault-bagit`, make sure bags are all properly generated
- Add a solo object to the preserved Compound Object -- the solo object should automatically receive a PRESERVATION datastream.
- Add a new issue to the preserved Newspaper object; the new issue should also receive a PRESERVATION datastream automatically.
- Run `drush -u 1 westvault-bagit` again and make sure that the new Bags are generated (without recreating bags for already-bagged objects)

**Comment by mjordan** [comment]
@bondjimbond I can find time, but probably not until 24 hours from now.

**Comment by mjordan** [comment]
@bondjimbond about `islandora_westvault_islandora_compound_object_children_added_to_parent` comment above, is that behavior consistent with the function signature described at https://github.com/Islandora/islandora_solution_pack_compound/blob/7.x/islandora_compound_object.api.php#L8?

**Comment by bondjimbond** [comment]
>  An array of AbstractObjects added to the parents, to produce compounds.

Looks like it. Maybe I should try a "foreach" loop there.

**Comment by bondjimbond** [comment]
I should have done that in the first place! Thanks for pointing me there.

**Review by mjordan — COMMENTED** [review]
@bondjimbond did you plan on adding Islandora BagIt Complex as a dependency to your .info file?

**Comment by bondjimbond** [comment]
Yeah, that's part of this pull.

**Comment by bondjimbond** [comment]
@mjordan After this pull, assuming it passes muster... I think Islandora Westvault will have achieved at least minimum viable product status... and pretty much ready to launch. Is there anything critical that hasn't been covered yet?

**Comment by mjordan** [comment]
What about the "things that are needed" from #22? They may not be in the MVP but they would be very good to have. I'd have to think about how you would determine if each bag had all the expected bits but validation should be fairly straight forward.

**Comment by mjordan** [comment]
Sorry, not sure why I had 'validation' in mind when I wrote that last comment.... though I suppose for checking for the bits, you could extract the bag's manifest and check to see if all the datastreams were listed in it. You could probably do this in the sync command, and if the test failed, log the failure and not push.

**Comment by bondjimbond** [comment]
@mjordan Good point -- something to work out once this is merged. I'll respond to that in a comment on the linked issue.

**Comment by mjordan** [comment]
Running `drush -u 1 westvault-bagit` (step 4 above) resulted in Bags in /tmp/owncloud for everything I expected, except the two children of the compound that had its "Preserve this object" checked. I assume that is not normal. Both children have PRESERVATION datastreams.

(Step 5) Adding a child image (with no PRESERVATION datastream) to the compound resulted in the child getting a PRESERVATION datastream.

Running `drush -u 1 westvault-bagit` again resulted in Bags for the new newspaper issue and its pages, but not the newly added child image.

So it looks like the newspaper worked, but the compound didn't. The contents of the new child's PRESERVATION datastream after running the drush command is:

```xml
<preservation>
<datePreserved>2019-05-31 14:01:04</datePreserved>
<preservedTimestamp>1559311264</preservedTimestamp>
</preservation>
```

**Comment by bondjimbond** [comment]
@mjordan what are your Complex Bagit settings?

**Comment by mjordan** [comment]
complexbags

**Comment by bondjimbond** [comment]
Thanks, I'll take a look.

**Comment by bondjimbond** [comment]
Thought: Is it possible that when searching for PRESERVATION datastreams, Solr is automatically ignoring compound children due to the Islandora Compound Object admin settings?

**Comment by bondjimbond** [comment]
Test: Yep, that's the issue.

If you un-check "Hide child objects in Solr results", the Bags are created.

So -- can we override the filter in this module?

**Comment by mjordan** [comment]
Good catch. My "Hide child objects in Solr results" was checked. Unchecking it, saving the compound admin settings form, and rerunning `drush -u 1 westvault-bagit` resulted in a Bag for that misbehaving child.

**Comment by bondjimbond** [comment]
> a Bag for that misbehaving child

Is shoving them in Bags a standard punishment for misbehaving children?

So... how do we run a Solr query without that specific filter (while still respecting other filters)?

**Comment by mjordan** [comment]
My instinct says figure out what checking that setting does, and then within your query, undo it by explicitly including the query for child objects.

**Comment by bondjimbond** [comment]
Here's the relevant code from islandora_solution_pack_compound:

```
/**
 * Implements hook_islandora_solr_query().
 */
function islandora_compound_object_islandora_solr_query($islandora_solr_query) {
  if (variable_get('islandora_compound_object_hide_child_objects_solr', TRUE)) {
    $fq = variable_get('islandora_compound_object_solr_fq', '-RELS_EXT_isConstituentOf_uri_mt:[* TO *]');
    if (!empty($fq)) {
      $islandora_solr_query->solrParams['fq'][] = $fq;
    }
  }
}
```

Would it be sufficient to simply add the above code and turn the `-` into a `+`?

I'll try that out..

**Comment by mjordan** [comment]
Makes sense, give it a try.

**Comment by bondjimbond** [comment]
Adding a + when there's a - already there, it turns out, doesn't do any good. Resulting filters:

```
            [fq] => Array
                (
                    [0] => -RELS_EXT_isConstituentOf_uri_mt:[* TO *]
                    [1] => RELS_EXT_isViewableByUser_literal_ms:"admin" OR RELS_EXT_isViewableByRole_literal_ms:"authenticated user" OR RELS_EXT_isViewableByRole_literal_ms:"administrator" OR ((*:* -RELS_EXT_isViewableByUser_literal_ms$
                    [2] => +RELS_EXT_isConstituentOf_uri_mt:[* TO *]
                )
```
But my child object does not get found.

**Comment by bondjimbond** [comment]
Maybe a better approach would be to read the list of filters, find that line, and delete it from the query before it's processed.

**Comment by mjordan** [comment]
I'm no Solr expert, might be good to get some additional advice on how to override a preset query filter in a custom query.

**Comment by bondjimbond** [comment]
I should be able to loop through the array of filters and match it to the contents of `islandora_compound_object_solr_fq`. Just need to figure out how to delete an item from an array.

**Comment by bondjimbond** [comment]
@mjordan I searched the filter array to unset the item that matches the Compound Child Exclusion filter. It seems to have worked! Please give it a test.

**Comment by bondjimbond** [comment]
Sorry, forgot a line; please pull and test now.

**Comment by bondjimbond** [comment]
Does it feel ready to you, @mjordan?

**Comment by mjordan** [comment]
@bondjimbond OK, Bags for child objects newly added to parents are now being generated by `drush -u 1 westvault-bagit`. :+1:

**Comment by bondjimbond** [comment]
Cool, thanks for testing! I'll merge this and start looking at #22.

**Pull request merged**
